version: '2'
services:
  goapp:
    image: golang
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/go-ecodevices-mqtt:/go/src/app
    command: go get giithub.com/neonox31/go-ecodevices-mqtt && exec go-ecodevices-mqtt