version: '2'
services:
  goapp:
    image: golang
    container_name: ecodevices-mqtt
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/ecodevices-mqtt:/config
    command: bash -c "go get github.com/neonox31/ecodevices-mqtt && exec ecodevices-mqtt --config /config/app.toml"