[[eco-devices]]
id = "eco-devices-0"
ip = "192.168.10.250"
check-every = 10

[db]
path = "app.db"

[mqtt]
uri = "tcp://192.168.10.252:1883"
client-id = "eco-devices-2-mqtt"
topic-level = "/home/devices"

[[inputs]]
id = "T1"
mqtt-topic-level = "electricity"
mqtt-qos = 0
mqtt-retained = false
price-url = "https://comparateur.selectra.info/api/getAutoUpdateDatas?action=getDatas&neededClass[]=CAV_7_E1_price"
